### PR TITLE
feat: setup lambda functions locally

### LINKED ISSUE #134: vercel prevents import request from completing
**Describe the bug**

Vercel has a 10-60 second runtime limit for requests. Our import request takes a few minutes to run because there is so much data.

**To Reproduce**

1. Log in as a language or platform admin
2. Go to the manage language page
3. Import glosses
4. Observe 504 timeout error

**Expected behavior**

The import should take a while, but it should complete.

### PR DESCRIPTION
**Pull request by Pertempto**
## What has changed

Setup lambda functions to run locally. We'll need to do additional configuration to get them running on AWS.

## Connected Issues

Related to #134 

## QA Steps

- [ ] Install SAM cli and Docker (see `contributing.md` for links)
- [ ] Run `npm i`
- [ ] Run `nx serve-functions lambda-functions`
- [ ] Try to access `localhost:3000/hello` through Postman.

## Post-Deployment

- [ ] Nothing required

### CODE REVIEW

**Comment by Pertempto** [comment]
These are just the bare minimum changes required to get it running locally.

**Review by arrocke — APPROVED** [review]
I haven't been able to set things up locally, but I don't want that to hold this up. It seems to work pretty well with nx, although one thing we will need to do is move the prisma code to a separate package so that both the lambda-functions and api project can use the same code. Up to you if you want to do that in this PR.

Can we document the setup steps that are necessary for lambda functions as optional? If they are only needed if you want to work on or test the import functionality, then I suspect in the long run, very few people will have to touch that.

I can work on getting this to deploy to AWS while you work on the code.

**Comment by Pertempto** [comment]
> Can we document the setup steps that are necessary for lambda functions as optional? If they are only needed if you want to work on or test the import functionality, then I suspect in the long run, very few people will have to touch that.

Yes, good idea! I will do that before merging.

> I can work on getting this to deploy to AWS while you work on the code.

Thanks! That would be very helpful.

**Comment by Pertempto** [comment]
Am I fine to merge, even though the api deployment is having issues?

**Comment by arrocke** [comment]
Yeah, I'll deal with that build failure separately if it keeps occurring. It's not caused by this PR.

**Pull request merged**
