### PR TITLE
fix: clean up brackets in the LSJ data

### LINKED ISSUE #262: Brackets in LSJ Data
**Describe the bug**
There are `[]` in the LSJ definitions that were surrounding the `<a></a>` tags, and mistakenly got left in.

**To Reproduce**
`SELECT * FROM public."LemmaResource" WHERE "resourceCode" = 'LSJ';`

**Expected behavior**
No `[]` in the LSJ definitions

### PR DESCRIPTION
**Pull request by Pertempto**
## What has changed

Cleaned up the leftover `[]` that were incorrectly left in the LSJ data.

## Connected Issues

#262 

## QA Steps

- [ ] Run `nx run db:import-lsj`
- [ ] Run `SELECT * FROM "LemmaResource" WHERE "resourceCode" = 'LSJ';` in your database
     - There should NOT be extra `[]` in the results

## Post-Deployment

- [ ] Run `nx run db:import-lsj` in the production DB

### CODE REVIEW

**Comment by Pertempto** [comment]
This branch includes the changes from #268, so that I could build my seed file off of that updated seed file.

**Comment by Pertempto** [comment]
I accidentally included my seed file changes in 103293ea536d71fa62dcd61cbff728c313dcb19c

**Review by arrocke — APPROVED** [review]
Does the seed file need to be rebuilt, or does it include changes from #268?

**Comment by Pertempto** [comment]
> Does the seed file need to be rebuilt, or does it include changes from #268?

See my [above comment](https://github.com/arrocke/gloss-translation/pull/271#issuecomment-1807734083). This seed file was built on the seed file from #268

**Comment by Pertempto** [comment]
I rebuilt the seed file to be sure everything was good.

**Pull request merged**
