### PR TITLE
feat: basic landing page for the root domain

### LINKED ISSUE #329: Landing page
[Here](https://www.figma.com/file/76F55N56TURolKVxMVKUGK/Design?type=design&node-id=97-253&mode=design&t=WXWv84dcKHItsgMA-0) is the design

### PR DESCRIPTION
**Pull request by arrocke**
## What has changed

* globalbibletools.com now points to a landing page to communicate the mission of what we are doing. It links to the interlinear translation site.
* there is a lot of work to be done yet on the landing page that I'll create other tickets for
  * drill down pages into each resource we are developing
  * roadmaps for our progress and future plans
  * illustrations to break up chunks of text
  * link to donate
  * automate deploys when merging to main

## Connected Issues

closes #329 

## QA Steps

1. Navigate to globalbibletools.com and confirm everything works as expected

## Post-Deployment

- [x] Nothing required

### CODE REVIEW

**Comment by Pertempto** [comment]
I hopefully can get to this on the 19th. Move ahead if you don't want to wait on me

**Comment by Pertempto** [comment]
@arrocke I didn't see an issue yet for responsive design of the landing page? That would be one I'd be very interested in handling

**Comment by arrocke** [comment]
I did that already in this PR

**Comment by Pertempto** [comment]
> I did that already in this PR

Ok, I see that now.

**Pull request merged**
